version: "2"

services:
  # constructor:

  server:
    build: .
    image: site-mapper
    depends_on:
      - database
    volumes:
      # Mount local
      - .:/sitemapper
      - front_public:/sitemapper/web/public
      - server_modules:/sitemapper/node_modules
      - server_bower:/sitemapper/bower_components
    ports:
      - 3000:3000
  database:
    image: mongo
    ports:
      - 27017:27017

volumes:
  front_public:
  server_modules:
  server_bower:
